W1010 13:21:15.211000 3600307 torch/distributed/elastic/multiprocessing/api.py:900] Sending process 3600328 closing signal SIGTERM
W1010 13:21:15.220000 3600307 torch/distributed/elastic/multiprocessing/api.py:900] Sending process 3600329 closing signal SIGTERM
W1010 13:21:15.221000 3600307 torch/distributed/elastic/multiprocessing/api.py:900] Sending process 3600331 closing signal SIGTERM
E1010 13:21:27.100000 3600307 torch/distributed/elastic/multiprocessing/api.py:874] failed (exitcode: -9) local_rank: 2 (pid: 3600330) of binary: /home/users/mendrika/virtual-env/DeepLearning/bin/python
Traceback (most recent call last):
  File "/home/users/mendrika/virtual-env/DeepLearning/bin/torchrun", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/users/mendrika/virtual-env/DeepLearning/lib/python3.12/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 355, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/users/mendrika/virtual-env/DeepLearning/lib/python3.12/site-packages/torch/distributed/run.py", line 892, in main
    run(args)
  File "/home/users/mendrika/virtual-env/DeepLearning/lib/python3.12/site-packages/torch/distributed/run.py", line 883, in run
    elastic_launch(
  File "/home/users/mendrika/virtual-env/DeepLearning/lib/python3.12/site-packages/torch/distributed/launcher/api.py", line 139, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/users/mendrika/virtual-env/DeepLearning/lib/python3.12/site-packages/torch/distributed/launcher/api.py", line 270, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
/home/users/mendrika/Zambia-Intercomparison/models/training/zambia-train.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2025-10-10_13:21:15
  host      : gpuhost016.jc.rl.ac.uk
  rank      : 2 (local_rank: 2)
  exitcode  : -9 (pid: 3600330)
  error_file: <N/A>
  traceback : Signal 9 (SIGKILL) received by PID 3600330
============================================================
slurmstepd: error: Detected 1 oom_kill event in StepId=45276164.batch. Some of the step tasks have been OOM Killed.
