/home/users/mendrika/virtual-env/DeepLearning/bin/python: can't open file '/home/users/mendrika/Zambia-Intercomparison/ ': [Errno 2] No such file or directory
E1010 13:27:50.182000 3600837 torch/distributed/elastic/multiprocessing/api.py:874] failed (exitcode: 2) local_rank: 0 (pid: 3600848) of binary: /home/users/mendrika/virtual-env/DeepLearning/bin/python
Traceback (most recent call last):
  File "/home/users/mendrika/virtual-env/DeepLearning/bin/torchrun", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/users/mendrika/virtual-env/DeepLearning/lib/python3.12/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 355, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/users/mendrika/virtual-env/DeepLearning/lib/python3.12/site-packages/torch/distributed/run.py", line 892, in main
    run(args)
  File "/home/users/mendrika/virtual-env/DeepLearning/lib/python3.12/site-packages/torch/distributed/run.py", line 883, in run
    elastic_launch(
  File "/home/users/mendrika/virtual-env/DeepLearning/lib/python3.12/site-packages/torch/distributed/launcher/api.py", line 139, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/users/mendrika/virtual-env/DeepLearning/lib/python3.12/site-packages/torch/distributed/launcher/api.py", line 270, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
  FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2025-10-10_13:27:50
  host      : gpuhost016.jc.rl.ac.uk
  rank      : 0 (local_rank: 0)
  exitcode  : 2 (pid: 3600848)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
/var/spool/slurmd/job45278043/slurm_script: line 43: --nproc_per_node=4: command not found
/var/spool/slurmd/job45278043/slurm_script: line 44: /home/users/mendrika/Zambia-Intercomparison/models/training/zambia-train.py: Permission denied
